#!/bin/bash

#Kasutaja kustutamine
if [ $# -ne 1 ]; then
    echo "Kasutusjuhend: $0 failinimi"
else
        failinimi=$1
  if [ -f $failinimi -a -r $failinimi ]; then
    echo "Kustutamine käivitatud"

 for nimi in $(cat $failinimi)
    do
      # sellega peaks faili sisu olema nähtav, kui fail on kätte saadav ja nüüd$
      #echo $nimi
PATH=$PATH:/usr/sbin
userdel -r -f $nimi # sellega me laseme kustutakasutaja skript tööle
    done
  else
    echo "probleem failiga $failinimi"
  fi
# parameetrite kontrolli lõpp
fi

#skripti lõpp
