#!/bin/bash

#Kasutaja kustutamine
if [ $# -ne 1 ]; then
    echo "Kasutusjuhend: $0 failinimi"
else
        failinimi=$1
  if [ -f $failinimi -a -r $failinimi ]; then
    echo "fail on korras"

 for nimi in $(cat $failinimi)
    do
      # sellega peaks faili sisu olema nähtav, kui fail on kätte saadav ja nüüd$
      #echo $nimi

PATH=$PATH:/usr/sbin
echo "tee on avatud"
userdel -f $nimi # sellega me laseme lisa_kasutaja skript tööle
    done
  else
    echo "probleem failiga $failinimi"
  fi
# parameetrite kontrolli lõpp
fi

#PATH=$PATH:/usr/sbin
#        read -p "Sisesta kustutava kasutaja nimi:$nimi "
#
#        do
#	deluser $nimi
#        echo "Kasutaja $UNAME on kustutatud" | grep "kasutaja" /etc/passwd
#done
